### ISSUE TITLE
About the csv problem in the data set

### ISSUE THREAD

**Issue by JelionNg** [ilyanovo/isic-2024#1]
metadata_df = pd.read_csv("../images/metadata.csv")
Excuse me, where is the metadata.csv here? I did not find this file in the dataset downloaded from Kaggle. Sorry to bother you.

**Comment by ilyanovo** [comment]
Hey! This one is from dataset download via isic cli. Check last few rows in notebooks/data_pull.ipynb

**Comment by JelionNg** [comment]
Thank you so much!



> Hey! This one is from dataset download via isic cli. Check last few rows in notebooks/data_pull.ipynb
