### ISSUE TITLE
NN-comp-experiments.ipynb File Missing

### ISSUE THREAD

**Issue by zrqzrq0** [ilyanovo/isic-2024#2]
Hi, I was going through the README and noticed that the NN-comp-experiments.ipynb file mentioned isn’t in the repo. Is it missing or should I be looking for a different file?

Thanks!

**Comment by ilyanovo** [comment]
Hi! Yes, that was an old name, you can use notebooks/NN-competition-train.ipynb

**Comment by zrqzrq0** [comment]
Thank you for your reply.
